### PR TITLE
[MT1O1-133] - Section 6 "Programación orientada a objetos" Tarea

### PR DESCRIPTION
**Pull request by ReyMtzO**
- Inside the package programacionOrientadaObjetos, I created the package tareaPOO
- Inside the package tareaPOO, I created the packages ejercicioUno and ejercicioDos
- Inside the package ejercicioUno, I worked in files enumClass.kt, programaUno.kt and the class Cuenta
- Inside the package ejercicioDos, I created the packages clases and enums
- Inside the package clases, I worked in classes Electrodomestico, Lavadora, Microondas and Refrigerador
- Inside the package enums, I worked in enum classes ColorElectrodomestico and TipoElectrodomestico, and the file Principal.kt

### CODE REVIEW

**Comment by fermudii** [comment]
Looks good!

**Comment by ReyMtzO** [comment]
@fermudii , Thanks! Any suggestions to improve the comments and annotations?

**Comment by fermudii** [comment]
@ReyMtzO You could try to write the comments in English! But it's just for English practice.

**Comment by ReyMtzO** [comment]
@fermudii Let's try that, thank you!

**Pull request merged**
